/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.app_gacha;

import static com.mycompany.app_gacha.Main.cont_lvl;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author joseb
 */
public class Evento2 extends javax.swing.JFrame {

    /**
     * Creates new form Evento1
     */
    public Evento2() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon("src\\main\\java\\images\\Torneo del Poder.png");
        Icon fondo = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(fondo);
        jLabel2.setText(Main.eventos.get(1).getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboNiveles = new javax.swing.JComboBox<>();
        jVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unleashing the Limit Breaker", "The Timeless Clash of Universes", "Battle Among Gods and Mortals", "Unveiling the True Potential", "Shadows of Destruction Descend", "Bonds Tested, Allies United", "An Unforeseen Twist of Fate", "Shattering the Boundaries of Power", "Roaring Chaos in the Arena", "A Universe on the Brink", "Reaching the Apex of Power", "The Symphony of Warriors", "The Desperate Gambit", "Striking Back Against Annihilation", "The Last Stand of Heroes", "Beyond the Realm of Mortals", "The Miraculous Revival", "Warriors of Indomitable Spirit", "The Battle for Survival Begins Anew", "The Legendary Champion Ascends" }));
        jPanel1.add(jComboNiveles, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jVolver.setText("<-");
        jVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 281));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 296, 220, 20));

        jPlay.setText("Play");
        jPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayActionPerformed(evt);
            }
        });
        jPanel1.add(jPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVolverActionPerformed
        MenuPrincipal mp = new MenuPrincipal();
        this.setVisible(false);
        mp.setVisible(true);
    }//GEN-LAST:event_jVolverActionPerformed

    private void jPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayActionPerformed
        Nivel lvl = new Nivel();
        switch (jComboNiveles.getSelectedIndex()) {
            case 0:
                cont_lvl = 41;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 1:
                cont_lvl = 42;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 2:
                cont_lvl = 43;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 3:
                cont_lvl = 44;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 4:
                cont_lvl = 45;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 5:
                cont_lvl = 46;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 6:
                cont_lvl = 47;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 7:
                cont_lvl = 48;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 8:
                cont_lvl = 49;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 9:
                cont_lvl = 50;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 10:
                cont_lvl = 51;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 11:
                cont_lvl = 52;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 12:
                cont_lvl = 53;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 13:
                cont_lvl = 54;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 14:
                cont_lvl = 55;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 15:
                cont_lvl = 56;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 16:
                cont_lvl = 57;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 17:
                cont_lvl = 58;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 18:
                cont_lvl = 59;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            case 19:
                cont_lvl = 60;
                this.setVisible(false);
                lvl.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evento2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evento2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboNiveles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPlay;
    private javax.swing.JButton jVolver;
    // End of variables declaration//GEN-END:variables
}
